<Project>
  <Import Project="$(MSBuildThisFileDirectory)Directory.Build.local.props"
          Condition="Exists('$(MSBuildThisFileDirectory)Directory.Build.local.props')" />

  <PropertyGroup>
    <RimWorldInstallDir Condition="'$(RimWorldInstallDir)' == ''">$(MSBuildThisFileDirectory)..\..\RimWorld</RimWorldInstallDir>
    <RimWorldWorkshopDir Condition="'$(RimWorldWorkshopDir)' == ''">$(MSBuildThisFileDirectory)..\..\..\..\workshop\content\294100</RimWorldWorkshopDir>
    <RimWorldManagedDir Condition="'$(RimWorldManagedDir)' == ''">$(RimWorldInstallDir)\RimWorldWin64_Data\Managed</RimWorldManagedDir>
    <AriandelLibraryDll Condition="'$(AriandelLibraryDll)' == ''">$(RimWorldWorkshopDir)\3665997350\1.6\Assemblies\AriandelLibrary.dll</AriandelLibraryDll>
    <ZAnimationModDll Condition="'$(ZAnimationModDll)' == ''">$(RimWorldWorkshopDir)\2944488802\1.6\Assemblies\zAnimationMod.dll</ZAnimationModDll>
  </PropertyGroup>
</Project>
